# -*- coding: utf-8 -*-
"""Script to recreate api/main.py with Google Sheets + FB Profile integration."""
import os

TARGET = os.path.join(os.path.dirname(os.path.dirname(__file__)), "api", "main.py")

CODE = (
    '# -*- coding: utf-8 -*-\n'
    '"""\n'
    'FastAPI Server for Facebook Messenger Webhook\n'
    'With Google Sheets logging and Facebook Profile integration\n'
    '"""\n'
    'import os\n'
    'import sys\n'
    'import asyncio\n'
    'import re as _re\n'
    'import html as _html\n'
    'from pathlib import Path\n'
    'from typing import List, Optional\n'
    'from contextlib import asynccontextmanager\n'
    '\n'
    'import requests\n'
    'from fastapi import FastAPI, Request, HTTPException, Query, BackgroundTasks\n'
    'from pydantic import BaseModel\n'
    'from dotenv import load_dotenv\n'
    '\n'
    'root_dir = Path(__file__).parent.parent\n'
    'sys.path.insert(0, str(root_dir))\n'
    '\n'
    'from core.initialize import initialize_system\n'
    '\n'
    'load_dotenv(root_dir / ".env")\n'
    '\n'
    'FB_PAGE_ACCESS_TOKEN = os.getenv("FB_PAGE_ACCESS_TOKEN")\n'
    'FB_VERIFY_TOKEN = os.getenv("FB_VERIFY_TOKEN")\n'
    'FB_GRAPH_API_URL = "https://graph.facebook.com/v19.0/me/messages"\n'
    '\n'
    'DOCUMENTS_DIR = root_dir / "data" / "documents"\n'
    'LINK_FILE = DOCUMENTS_DIR / "Link_nguon.md"\n'
    '_drive_links: dict = {}\n'
    '\n'
    '\n'
    'def load_drive_links():\n'
    '    global _drive_links\n'
    '    if not LINK_FILE.exists():\n'
    '        print("[DriveLinks] Link_nguon.md not found")\n'
    '        return\n'
    '    text = LINK_FILE.read_text(encoding="utf-8")\n'
    '    lines = text.splitlines()\n'
    '    merged = []\n'
    '    i = 0\n'
    '    while i < len(lines):\n'
    '        line = lines[i].strip()\n'
    '        if not line:\n'
    '            i += 1\n'
    '            continue\n'
    '        if (line.endswith(":") or ":" not in line) and i + 1 < len(lines):\n'
    '            next_line = lines[i + 1].strip()\n'
    '            if next_line.startswith("http"):\n'
    '                merged.append(f"{line.rstrip(chr(58))} : {next_line}")\n'
    '                i += 2\n'
    '                continue\n'
    '        merged.append(line)\n'
    '        i += 1\n'
    '    for entry in merged:\n'
    '        if " : " in entry:\n'
    '            name_part, url_part = entry.split(" : ", 1)\n'
    '        elif ": http" in entry:\n'
    '            idx = entry.index(": http")\n'
    '            name_part = entry[:idx]\n'
    '            url_part = entry[idx + 2:]\n'
    '        else:\n'
    '            continue\n'
    '        stem = name_part.strip()\n'
    '        for ext in (".pptm", ".pptx", ".pdf", ".docx", ".doc", ".md"):\n'
    '            stem = stem.replace(ext, "")\n'
    '        _drive_links[stem.strip().lower()] = url_part.strip()\n'
    '    print(f"[DriveLinks] Loaded {len(_drive_links)} links")\n'
    '\n'
    '\n'
    'def get_drive_links_for_sources(sources):\n'
    '    if not _drive_links:\n'
    '        load_drive_links()\n'
    '    result = {}\n'
    '    for src in sources:\n'
    '        src_lower = src.strip().lower()\n'
    '        if src_lower in _drive_links:\n'
    '            result[src] = _drive_links[src_lower]\n'
    '            continue\n'
    '        for key, url in _drive_links.items():\n'
    '            if src_lower in key or key in src_lower:\n'
    '                result[src] = url\n'
    '                break\n'
    '    return result\n'
    '\n'
    '\n'
    'load_drive_links()\n'
    '\n'
    '# ======== Google Sheets Logging ========\n'
    'from src.google_sheets_handler import GoogleSheetsLogger\n'
    'gs_logger = GoogleSheetsLogger()\n'
    '\n'
    '# ======== Facebook User Profile Cache ========\n'
    '_user_names = {}\n'
    '\n'
    '\n'
    'def fetch_fb_user_name(user_id):\n'
    '    """Fetch user name from Facebook Graph API."""\n'
    '    global _user_names\n'
    '    if user_id in _user_names:\n'
    '        return _user_names[user_id]\n'
    '    try:\n'
    '        url = f"https://graph.facebook.com/v19.0/{user_id}"\n'
    '        params = {"fields": "first_name,last_name", "access_token": FB_PAGE_ACCESS_TOKEN}\n'
    '        resp = requests.get(url, params=params, timeout=5)\n'
    '        if resp.status_code == 200:\n'
    '            data = resp.json()\n'
    '            full_name = (data.get("last_name", "") + " " + data.get("first_name", "")).strip()\n'
    '            if full_name:\n'
    '                _user_names[user_id] = full_name\n'
    '                print(f"[FB] Name for {user_id}: {full_name}")\n'
    '                return full_name\n'
    '    except Exception as e:\n'
    '        print(f"[FB] Profile error: {e}")\n'
    '    fallback = f"User_{user_id[-4:]}"\n'
    '    _user_names[user_id] = fallback\n'
    '    return fallback\n'
    '\n'
    '\n'
    '@asynccontextmanager\n'
    'async def lifespan(app_instance):\n'
    '    from src.document_loader import DocumentMonitor\n'
    '    monitor = DocumentMonitor()\n'
    '    updates = monitor.check_updates()\n'
    '    if updates:\n'
    '        print(f"WARNING: {len(updates)} documents need re-indexing!")\n'
    '    else:\n'
    '        print("Vector store is up to date.")\n'
    '    yield\n'
    '\n'
    '\n'
    'app = FastAPI(title="HaUI Chatbot Facebook API", lifespan=lifespan)\n'
    'workflow = None\n'
    'conversation_manager = None\n'
    'init_lock = asyncio.Lock()\n'
    '\n'
    '\n'
    'async def get_chatbot():\n'
    '    global workflow, conversation_manager\n'
    '    async with init_lock:\n'
    '        if workflow is None:\n'
    '            print("Initializing Chatbot System...")\n'
    '            from concurrent.futures import ThreadPoolExecutor\n'
    '            loop = asyncio.get_event_loop()\n'
    '            with ThreadPoolExecutor() as pool:\n'
    '                workflow, conversation_manager, _ = await loop.run_in_executor(pool, initialize_system)\n'
    '    return workflow, conversation_manager\n'
    '\n'
    '\n'
    '@app.get("/health")\n'
    'async def health_check():\n'
    '    return {"status": "ok"}\n'
    '\n'
    '\n'
    '@app.get("/webhook")\n'
    'async def verify_webhook(\n'
    '    mode: str = Query(None, alias="hub.mode"),\n'
    '    token: str = Query(None, alias="hub.verify_token"),\n'
    '    challenge: str = Query(None, alias="hub.challenge"),\n'
    '):\n'
    '    if mode == "subscribe" and token == FB_VERIFY_TOKEN:\n'
    '        print("WEBHOOK_VERIFIED")\n'
    '        return int(challenge)\n'
    '    raise HTTPException(status_code=403, detail="Verification failed")\n'
    '\n'
    '\n'
    '@app.post("/webhook")\n'
    'async def handle_messages(request: Request, background_tasks: BackgroundTasks):\n'
    '    try:\n'
    '        data = await request.json()\n'
    '    except Exception:\n'
    '        return "EMPTY_BODY"\n'
    '    if data.get("object") == "page":\n'
    '        for entry in data.get("entry", []):\n'
    '            for event in entry.get("messaging", []):\n'
    '                msg = event.get("message", {})\n'
    '                if msg and "text" in msg:\n'
    '                    sid = event["sender"]["id"]\n'
    '                    txt = msg["text"]\n'
    '                    print(f"Received from {sid}: {txt}")\n'
    '                    background_tasks.add_task(process_and_reply, sid, txt)\n'
    '        return "EVENT_RECEIVED"\n'
    '    raise HTTPException(status_code=404)\n'
    '\n'
    '\n'
    'async def process_and_reply(sender_id: str, message_text: str):\n'
    '    """Process message via RAG and reply, with logging to MongoDB + Google Sheets."""\n'
    '    user_name = fetch_fb_user_name(sender_id)\n'
    '    wf, conv_mgr = await get_chatbot()\n'
    '    try:\n'
    '        session_id = f"fb_{sender_id}"\n'
    '        chat_history = conv_mgr.get_history(session_id, limit=10)\n'
    '        result = wf.run(message_text, session_id=session_id, chat_history=chat_history)\n'
    '        answer = result["answer"]\n'
    '\n'
    '        # Log to MongoDB\n'
    '        conv_mgr.add_message(session_id, "user", message_text, metadata={"user_name": user_name})\n'
    '        conv_mgr.add_message(session_id, "assistant", answer, sources=result.get("sources"))\n'
    '\n'
    '        # Log to Google Sheets\n'
    '        gs_logger.append_log(\n'
    '            user_name=user_name,\n'
    '            user_id=sender_id,\n'
    '            question=message_text,\n'
    '            answer=answer,\n'
    '            sources=result.get("sources"),\n'
    '            relevance=result.get("relevance_score", 0.0),\n'
    '        )\n'
    '\n'
    '        send_fb_message(sender_id, answer)\n'
    '\n'
    '        if result.get("sources"):\n'
    '            drive_links = get_drive_links_for_sources(result["sources"])\n'
    '            lines = []\n'
    '            for src in result["sources"]:\n'
    '                if src in drive_links:\n'
    '                    lines.append(f"- {src}\\n  Link: {drive_links[src]}")\n'
    '                else:\n'
    '                    lines.append(f"- {src}")\n'
    '            sources_text = "Nguon tham khao:\\n" + "\\n".join(lines)\n'
    '            send_fb_message(sender_id, sources_text)\n'
    '    except Exception as e:\n'
    '        print(f"Error: {e}")\n'
    '        send_fb_message(sender_id, "Xin loi, toi gap su co ky thuat. Vui long thu lai sau.")\n'
    '\n'
    '\n'
    'def _html_to_plain(text):\n'
    '    text = _html.unescape(text)\n'
    '    text = _re.sub(r"<br\\\\s*/?>", "\\n", text, flags=_re.IGNORECASE)\n'
    '    text = _re.sub(r"</?p\\\\s*>", "\\n", text, flags=_re.IGNORECASE)\n'
    '    text = _re.sub(r"<li\\\\s*>", "\\n- ", text, flags=_re.IGNORECASE)\n'
    '    text = _re.sub(r"<[^>]+>", "", text)\n'
    '    text = _re.sub(r"\\n{3,}", "\\n\\n", text)\n'
    '    return text.strip()\n'
    '\n'
    '\n'
    'def send_fb_message(recipient_id, message_text):\n'
    '    message_text = _html_to_plain(message_text)\n'
    '    MAX_LEN = 1900\n'
    '    chunks = [message_text[i:i + MAX_LEN] for i in range(0, len(message_text), MAX_LEN)]\n'
    '    params = {"access_token": FB_PAGE_ACCESS_TOKEN}\n'
    '    headers = {"Content-Type": "application/json"}\n'
    '    for chunk in chunks:\n'
    '        payload = {"recipient": {"id": recipient_id}, "message": {"text": chunk}}\n'
    '        resp = requests.post(FB_GRAPH_API_URL, params=params, headers=headers, json=payload)\n'
    '        if resp.status_code != 200:\n'
    '            print(f"FB send error: {resp.status_code} - {resp.text}")\n'
    '        else:\n'
    '            print(f"Message sent to {recipient_id}")\n'
    '\n'
    '\n'
    'if __name__ == "__main__":\n'
    '    import uvicorn\n'
    '    uvicorn.run(app, host="0.0.0.0", port=8000)\n'
)

os.makedirs(os.path.dirname(TARGET), exist_ok=True)
with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
    f.write(CODE)

print(f"OK: wrote {len(CODE)} chars to {TARGET}")
